### ISSUE TITLE
✨ [Feature Request]  Antidelete feature 

### ISSUE THREAD

**Issue by Korretdesigns** [hacxk/Buddy-MD#2]
### What should we call this feature? 🏷️💭

antidelete

### What's this feature all about? 🚀🔍

This feature would allow the bot to forward revoked/deleted messages to the owner number with details of where, when the message was deleted P.S: the message should be sent to the owner number immediately the message was deleted 

### How would people use this feature? 🎯👥

For example, I would use this feature to get deleted messages for fun 

### How important is this feature to you? 🌟🔥

Nice to have 😊

### Code of Conduct 📜🤝

- [X] I agree to follow the project's Code of Conduct 🤓✅

**Comment by hacxk** [comment]
Thanks for submitting the feature request for an anti-delete functionality.

 We understand the potential value in tracking deleted messages, especially for moderation or record-keeping purposes.

We've logged your request and will take it into consideration as we plan future development. Keep in mind that privacy implications and technical feasibility will need to be carefully assessed.

We appreciate your proactive contributions to improving Buddy-MD!

**Comment by Korretdesigns** [comment]
Can i get your contact like whatsapp?

**Comment by Korretdesigns** [comment]
I have questions about the database sqlite cause i'm facing problems about it

**Comment by hacxk** [comment]
> Can i get your contact like whatsapp?

Yeah I AM In Discord Username: hacxk
